### ISSUE TITLE
Consider changing the license to something applicable to software

### ISSUE THREAD

**Issue by madeso** [AndrewBelt/osdialog#8]
Even creative commons suggest not using cc on software/code, perhaps something like mit, zlib or isc

> We recommend against using Creative Commons licenses for software. Instead, we strongly encourage you to use one of the very good software licenses which are already available. We recommend considering licenses made available by the Free Software Foundation or listed as “open source” by the Open Source Initiative.
> 
> Unlike software-specific licenses, CC licenses do not contain specific terms about the distribution of source code, which is often important to ensuring the free reuse and modifiability of software. Many software licenses also address patent rights, which are important to software but may not be applicable to other copyrightable works. Additionally, our licenses are currently not compatible with the major software licenses, so it would be difficult to integrate CC-licensed work with other free software. Existing software licenses were designed specifically for use with software and offer a similar set of rights to the Creative Commons licenses.
> 
> Version 4.0 of CC's Attribution-ShareAlike (BY-SA) license is one-way compatible with the GNU General Public License version 3.0 (GPLv3). This compatibility mechanism is designed for situations in which content is integrated into software code in a way that makes it difficult or impossible to distinguish the two. There are special considerations required before using this compatibility mechanism. Read more about it here.
> 
> Also, the CC0 Public Domain Dedication is GPL-compatible and acceptable for software. For details, see the relevant CC0 FAQ entry.
> 
> While we recommend against using a CC license on software itself, CC licenses may be used for software documentation, as well as for separate artistic elements such as game art or music.

https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

https://opensource.stackexchange.com/questions/133/how-could-using-code-released-under-cc0-infringe-on-the-authors-patents

**Comment by r-lyeh** [comment]
closest to cc0 is unlicensing. mit/isc are way more restrictive

**Comment by AndrewBelt** [comment]
>Also, the CC0 Public Domain Dedication is GPL-compatible and acceptable for software. For details, [see the relevant CC0 FAQ entry](https://wiki.creativecommons.org/wiki/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F).

Quoting from the text you quoted itself.

**Comment by ghost** [comment]
Things changed a bit recently regarding this. Quoting the [Unlicense](https://en.wikipedia.org/wiki/Unlicense) article from Wikipedia:

> Until 2022, the Fedora Project recommended CC0 over the Unlicense because [the former is "a more comprehensive legal text"](https://fedoraproject.org/wiki/Licensing/Unlicense). However, in July 2022, the CC0 license became unsupported and software to be released in the Fedora distribution must not be under CC0, due to [CC0 not waiving patent rights](https://www.theregister.com/2022/07/25/fedora_sours_on_creative_commons/)

So, Fedora stopped distributing CC0-based software due to this concern, and other distributions might follow. Because Zlib/ISC/MIT are too restrictive compared to CC0, maybe the Unlicense or the 0-Clause BSD (BSD0) are suitable replacements.

**Comment by AndrewBelt** [comment]
I don't claim any patent rights, so there are none I can waive.
